version: '3'

services:
  app:
    build: .
    container_name: heat-tags-app
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 4000:4000
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
  db:
    build: .docker/postgres
    container_name: heat-tags-db
    restart: always
    tty: true
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=heat_tags_dev
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: heat-tags-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 9000:80
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
